### ISSUE TITLE
LWRP names incorrect when using provides

### ISSUE THREAD

**Issue by joerg** [rightscale-cookbooks/yard-chef#11]
LWRP names seem to be generated automatically using <coobkook_name>_<resource_name> which is correct for definitions, but not necessarily for LWRPs. According to the chef docs a "provides" can be defined, which specifies the LWRPs name (https://docs.chef.io/lwrp_custom_resource.html#provides).

**Comment by rshade** [comment]
@joerg can you test with 2.0, and let me know

**Comment by joerg** [comment]
Hi,

Glad to see that this project is being revived, but since it was dead so long I chose to work on my own project https://github.com/chefdoc which supports a more modern, cookbook centric, approach to this and it also has its own service at https://www.chefdoc.info/ modelled after rubydoc.info.
Anyways, you can close this issue if you think it is resolved.

**Comment by rshade** [comment]
@joerg awesome good to hear man. It looks nice
