### ISSUE TITLE
Mode to treat cookbook as root object

### ISSUE THREAD

**Issue by jhulten** [rightscale-cookbooks/yard-chef#9]
Currently the plugin treats a repository as the root level object. For those of us that publish public cookbooks or have a workflow heavily informed by Berkshelf it would be nice to be able to treat our cookbook as the root of the documentation.

We don't generate documentation for an entire Gemfile, just for the gem we are developing. I think we should at least support the option for the same behavior.

**Comment by rshade** [comment]
Looks to be solved, closing, if still a problem please re-open
